name: PR Checker
on:
  pull_request:
    # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened. 
    types: [opened, synchronize, reopened, edited]
    

jobs:
  get-recommendation:
    runs-on: ubuntu-latest
    name: Get a PR recommendation from OpenAI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get AI comment
        uses: WesternHemlock/openai-for-prs@main
        with:
          openai-token: ${{ secrets.OPENAI_API_KEY }}
          tokens: 2500
          pr-title: "${{ github.event.pull_request.title }}"
          pr-author: "${{ github.event.pull_request.user.login }}"
